Repository Hexastack/Hexabot, pull requests merged in 2025-03, with the labels that each got.

#784 feat: delete invitation on role delete
  api/src/chat/controllers/block.controller.spec.ts
  api/src/chat/controllers/label.controller.spec.ts
  api/src/chat/controllers/message.controller.spec.ts
  api/src/chat/controllers/subscriber.controller.spec.ts
  api/src/chat/services/message.service.spec.ts
  api/src/chat/services/subscriber.service.spec.ts
  api/src/user/controllers/model.controller.spec.ts
  api/src/user/controllers/permission.controller.spec.ts
  api/src/user/controllers/role.controller.spec.ts
  api/src/user/repositories/permission.repository.spec.ts
  api/src/user/repositories/role.repository.spec.ts
  api/src/user/repositories/role.repository.ts
  api/src/user/repositories/user.repository.spec.ts
  api/src/user/services/auth.service.spec.ts
  api/src/user/services/passwordReset.service.spec.ts
  api/src/user/services/permission.service.spec.ts
  api/src/user/services/role.service.spec.ts
  api/src/user/services/user.service.spec.ts
  api/src/user/services/validate-account.service.spec.ts
Labels: needs-review

#802 fix(api): align deleteMany ids type with value
  api/src/chat/controllers/block.controller.ts
  api/src/chat/controllers/category.controller.ts
  api/src/chat/controllers/context-var.controller.ts
  api/src/chat/controllers/label.controller.ts
  api/src/nlp/controllers/nlp-entity.controller.ts
  api/src/nlp/controllers/nlp-sample.controller.ts
  api/src/nlp/controllers/nlp-value.controller.ts
Labels: enhancement

#792 feat: nlu keyword entity annotation
  api/src/nlp/controllers/nlp-sample.controller.ts
  api/src/nlp/services/nlp-sample-entity.service.spec.ts
  api/src/nlp/services/nlp-sample-entity.service.ts
  api/src/nlp/services/nlp-sample.service.spec.ts
  api/src/nlp/services/nlp-sample.service.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/app-components/tables/columns/getColumns.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/services/api.class.ts
Labels: needs-review

#833 fix: disabled minimize option for conversation schema
  api/src/chat/schemas/conversation.schema.ts
  api/src/chat/services/bot.service.spec.ts
Labels: bug

#831 feat: add emitAsync support
  api/src/chat/repositories/subscriber.repository.spec.ts
  api/src/utils/generics/base-repository.ts
  api/types/event-emitter.d.ts
Labels: enhancement

#820 fix: synchronized sent messages cross account tabs
  api/src/chat/services/chat.service.ts
Labels: bug

#846 fix: move canPopulate method to the base-repository
  api/src/utils/generics/base-controller.ts
  api/src/utils/generics/base-repository.ts
  api/src/utils/generics/base-service.ts
Labels: enhancement
