Repository Hexastack/Hexabot, pull requests merged in 2025-05, with the labels that each got.

#953 fix: undefined subscriber
  api/src/chat/services/chat.service.ts
Labels: needs-review, urgent, v2.2.6

#965 fix: resolve show more button issue
  api/src/chat/services/bot.service.ts
Labels: bug

#958 fix: validation bypass when updating block
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/app-components/tabs/TabPanel.tsx
  frontend/src/components/visual-editor/BlockEditForm.tsx
Labels: needs-review, v2.2.6

#954 fix: auto navigate to new flow after creation
  frontend/src/components/categories/CategoryForm.tsx
Labels: needs-review

#957 fix: llm nlu confidence
  api/src/extensions/helpers/llm-nlu/index.helper.ts
Labels: needs-review

#970 Handle context update conflicts
  api/src/chat/services/bot.service.ts
  api/src/chat/services/conversation.service.ts
  api/src/utils/generics/base-repository.spec.ts
  api/src/utils/generics/base-repository.ts
  api/src/utils/generics/base-service.ts
  api/src/utils/helpers/flatten.spec.ts
  api/src/utils/helpers/flatten.ts
  api/src/utils/test/dummy/schemas/dummy.schema.ts
  api/src/utils/types/filter.types.ts
Labels: bug

#984 refactor(frontend): apply useDialogs props names changes
  frontend/src/app-components/attachment/AttachmentForm.tsx
  frontend/src/app-components/attachment/AttachmentFormDialog.tsx
  frontend/src/app-components/attachment/AttachmentUploader.tsx
  frontend/src/app-components/dialogs/GenericFormDialog.tsx
  frontend/src/components/Menu/MenuForm.tsx
  frontend/src/components/Menu/MenuFormDialog.tsx
  frontend/src/components/Menu/index.tsx
  frontend/src/components/categories/CategoryForm.tsx
  frontend/src/components/categories/CategoryFormDialog.tsx
  frontend/src/components/categories/index.tsx
  frontend/src/components/content-types/ContentTypeForm.tsx
  frontend/src/components/content-types/ContentTypeFormDialog.tsx
  frontend/src/components/content-types/index.tsx
  frontend/src/components/contents/ContentForm.tsx
  frontend/src/components/contents/ContentFormDialog.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/components/context-vars/ContextVarForm.tsx
  frontend/src/components/context-vars/ContextVarFormDialog.tsx
  frontend/src/components/context-vars/index.tsx
  frontend/src/components/inbox/components/AttachmentViewer.tsx
  frontend/src/components/inbox/components/AttachmentViewerForm.tsx
  frontend/src/components/inbox/components/AttachmentViewerFormDialog.tsx
  frontend/src/components/labels/LabelForm.tsx
  frontend/src/components/labels/LabelFormDialog.tsx
  frontend/src/components/labels/index.tsx
  frontend/src/components/languages/LanguageForm.tsx
  frontend/src/components/languages/LanguageFormDialog.tsx
  frontend/src/components/languages/index.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/components/nlp/components/NlpEntityFormDialog.tsx
  frontend/src/components/nlp/components/NlpSample.tsx
  frontend/src/components/nlp/components/NlpSampleForm.tsx
  frontend/src/components/nlp/components/NlpSampleFormDialog.tsx
  frontend/src/components/nlp/components/NlpValueForm.tsx
  frontend/src/components/nlp/components/NlpValueFormDialog.tsx
  frontend/src/components/roles/PermissionsBody.tsx
  frontend/src/components/roles/PermissionsBodyDialog.tsx
  frontend/src/components/roles/RoleForm.tsx
  frontend/src/components/roles/RoleFormDialog.tsx
  frontend/src/components/roles/index.tsx
  frontend/src/components/subscribers/SubscriberForm.tsx
  frontend/src/components/subscribers/SubscriberFormDialog.tsx
  frontend/src/components/subscribers/index.tsx
  frontend/src/components/translations/TranslationForm.tsx
  frontend/src/components/translations/TranslationFormDialog.tsx
  frontend/src/components/translations/index.tsx
  frontend/src/components/users/EditUserForm.tsx
  frontend/src/components/users/EditUserFormDialog.tsx
  frontend/src/components/users/InviteUserFormDialog.tsx
  frontend/src/components/users/index.tsx
  frontend/src/components/visual-editor/BlockEditForm.tsx
  frontend/src/components/visual-editor/BlockEditFormDialog.tsx
  frontend/src/components/visual-editor/BlockMoveForm.tsx
  frontend/src/components/visual-editor/BlockMoveFormDialog.tsx
  frontend/src/components/visual-editor/v2/Diagrams.tsx
  frontend/src/types/common/dialogs.types.ts
Labels: enhancement

#1000 Feat/implement block nlp prioritization strategy v3
  api/src/chat/chat.module.ts
  api/src/chat/controllers/block.controller.spec.ts
  api/src/chat/services/block.service.spec.ts
  api/src/chat/services/block.service.ts
  api/src/chat/services/bot.service.spec.ts
  api/src/chat/services/chat.service.ts
  api/src/helper/lib/__test__/base-nlp-helper.spec.ts
  api/src/helper/types.ts
  api/src/i18n/controllers/translation.controller.spec.ts
  api/src/i18n/services/language.service.ts
  api/src/nlp/controllers/nlp-entity.controller.spec.ts
  api/src/nlp/controllers/nlp-entity.controller.ts
  api/src/nlp/controllers/nlp-sample.controller.spec.ts
  api/src/nlp/controllers/nlp-value.controller.spec.ts
  api/src/nlp/dto/nlp-entity.dto.ts
  api/src/nlp/nlp.module.ts
  api/src/nlp/repositories/nlp-entity.repository.spec.ts
  api/src/nlp/repositories/nlp-value.repository.spec.ts
  api/src/nlp/schemas/nlp-entity.schema.ts
  api/src/nlp/schemas/types.ts
  api/src/nlp/services/nlp-entity.service.spec.ts
  api/src/nlp/services/nlp-entity.service.ts
  api/src/nlp/services/nlp-sample-entity.service.spec.ts
  api/src/nlp/services/nlp-sample.service.spec.ts
  api/src/nlp/services/nlp-value.service.spec.ts
  api/src/nlp/services/nlp.service.spec.ts
  api/src/nlp/services/nlp.service.ts
  api/src/utils/constants/cache.ts
  api/src/utils/test/fixtures/nlpentity.ts
  api/src/utils/test/fixtures/nlpvalue.ts
  api/src/utils/test/mocks/block.ts
  api/src/utils/test/mocks/nlp.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/app-components/tables/columns/getColumns.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/types/nlp-entity.types.ts
Labels: needs-review

#1001 fix: disalow attachment delete
  api/src/attachment/controllers/attachment.controller.spec.ts
  api/src/attachment/controllers/attachment.controller.ts
  frontend/src/app-components/attachment/AttachmentThumbnail.tsx
Labels: needs-review

#1008 fix(frontend): update dialogs types
  frontend/src/components/languages/index.tsx
  frontend/src/components/visual-editor/v2/Diagrams.tsx
  frontend/src/types/common/dialogs.types.ts
Labels: bug

#999 refactor: subscriber avatar store
  api/src/chat/services/bot.service.spec.ts
  api/src/chat/services/chat.service.ts
  api/src/chat/services/subscriber.service.spec.ts
  api/src/chat/services/subscriber.service.ts
  api/src/user/user.module.ts
Labels: needs-review

#995 fix: Show quick replies in Console Chat Widget
  api/src/chat/services/message.service.spec.ts
  api/src/chat/services/message.service.ts
  api/src/chat/services/subscriber.service.spec.ts
  api/src/chat/services/subscriber.service.ts
  api/src/websocket/pipes/io-message.pipe.ts
  api/src/websocket/utils/gateway-options.ts
  api/src/websocket/utils/socket-response.ts
  api/src/websocket/websocket.gateway.spec.ts
  api/src/websocket/websocket.gateway.ts
  frontend/src/components/inbox/hooks/ChatContext.tsx
  frontend/src/layout/AnonymousLayout.tsx
  frontend/src/layout/AuthenticatedLayout.tsx
  frontend/src/layout/Header.tsx
  frontend/src/layout/index.tsx
  widget/src/components/UserSubscription.tsx
  widget/src/providers/ChatProvider.tsx
Labels: bug, needs-review

#1014 fix(api): add check contextValue check
  api/src/chat/services/conversation.service.ts
Labels: bug

#1028 fix: resolve block list bug
  api/src/chat/schemas/types/button.ts
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
Labels: bug

#1035 fix(frontend): select components defaultValue
  frontend/src/app-components/inputs/AutoCompleteEntitySelect.tsx
  frontend/src/app-components/inputs/AutoCompleteSelect.tsx
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
Labels: bug, needs-review

#1038 fix(frontend): rename display_mode field
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
Labels: needs-review

#1041 fix(api): add missing field to NlpEntityUpdateDto
  api/src/nlp/dto/nlp-entity.dto.ts
Labels: bug, needs-review

#1029 fix(frontend): update incorrect translation keys
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/app-components/auth/Login.tsx
  frontend/src/app-components/auth/Register.tsx
  frontend/src/app-components/auth/ResetPassword.tsx
  frontend/src/components/profile/profile.tsx
  frontend/src/components/settings/SettingInput.tsx
  frontend/src/components/users/EditUserForm.tsx
Labels: bug, needs-review

#1052 Fix/use search v3
  frontend/src/app-components/attachment/AttachmentUploader.tsx
  frontend/src/app-components/inputs/FilterTextfield.tsx
  frontend/src/app-components/svg/NoDataIcon.tsx
  frontend/src/app-components/tables/DataGrid.tsx
  frontend/src/app-components/tables/NoDataOverlay.tsx
  frontend/src/components/categories/index.tsx
  frontend/src/components/content-types/index.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/components/context-vars/index.tsx
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/components/inbox/index.tsx
  frontend/src/components/labels/index.tsx
  frontend/src/components/languages/index.tsx
  frontend/src/components/media-library/index.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpSample.tsx
  frontend/src/components/nlp/components/NlpValue.tsx
  frontend/src/components/roles/index.tsx
  frontend/src/components/subscribers/index.tsx
  frontend/src/components/translations/index.tsx
  frontend/src/components/users/index.tsx
  frontend/src/hooks/crud/useFind.tsx
  frontend/src/hooks/crud/useInfiniteFind.ts
  frontend/src/hooks/useSearch.tsx
  frontend/src/hooks/useUrlQueryParam.ts
  frontend/src/utils/URL.ts
Labels: needs-review

#1048 Add default NLU penalty factor and async support for NLP matching
  api/src/chat/services/block.service.spec.ts
  api/src/chat/services/block.service.ts
  api/src/setting/seeds/setting.seed-model.ts
  api/src/utils/constants/nlp.ts
  frontend/public/locales/en/chatbot_settings.json
  frontend/public/locales/fr/chatbot_settings.json
Labels: needs-review

#1062 fix(frontend): remove duplicated inbox page
  frontend/src/pages/inbox.tsx
Labels: needs-review

#1059 fix(frontend): add limit validation based on block list type
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
Labels: bug, needs-review

#1054 Add URL auto-linking for chat messages in the inbox page
  frontend/package.json
  frontend/src/components/inbox/helpers/mapMessages.tsx
  frontend/src/components/inbox/inbox.css
Labels: needs-review

#1057 feat(api): add migration script v2.2.9
  api/src/migration/migrations/1748492346868-v-2-2-9.migration.ts
Labels: needs-review

#1049 Implement prompt building during application bootstrap for LlmNluHelper
  api/src/extensions/helpers/llm-nlu/index.helper.ts
Labels: needs-review

#1066 fix: resolve duplicated subscriber issue
  api/package-lock.json
  api/package.json
  api/src/channel/channel.service.ts
  api/src/websocket/services/socket-event-dispatcher.service.ts
  frontend/src/app-components/widget/ChatWidget.tsx
Labels: bug, needs-review
