Repository Hexastack/Hexabot, pull requests merged in 2025-02, with the labels that each got.

#684 refactor(frontend): update translation dialogs
  frontend/src/components/translations/EditTranslationDialog.tsx
  frontend/src/components/translations/TranslationForm.tsx
  frontend/src/components/translations/TranslationFormDialog.tsx
  frontend/src/components/translations/TranslationInput.tsx
  frontend/src/components/translations/index.tsx
Labels: enhancement

#686 refactor(frontend): update contextVar dialogs
  frontend/src/components/context-vars/ContextVarDialog.tsx
  frontend/src/components/context-vars/ContextVarForm.tsx
  frontend/src/components/context-vars/ContextVarFormDialog.tsx
  frontend/src/components/context-vars/index.tsx
Labels: enhancement

#688 refactor(frontend): update label dialogs
  frontend/src/components/labels/LabelDialog.tsx
  frontend/src/components/labels/LabelForm.tsx
  frontend/src/components/labels/LabelFormDialog.tsx
  frontend/src/components/labels/index.tsx
Labels: enhancement

#673 fix: broadcast channel provider missing for widget
  widget/src/ChatWidget.tsx
Labels: needs-review

#693 refactor(frontend): implement GenericFormDialog component
  frontend/src/app-components/dialogs/GenericFormDialog.tsx
  frontend/src/app-components/dialogs/index.ts
  frontend/src/components/categories/CategoryFormDialog.tsx
  frontend/src/components/context-vars/ContextVarFormDialog.tsx
  frontend/src/components/labels/LabelFormDialog.tsx
  frontend/src/components/translations/TranslationFormDialog.tsx
Labels: refactor

#690 refactor(frontend): update language dialogs
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/components/languages/LanguageDialog.tsx
  frontend/src/components/languages/LanguageForm.tsx
  frontend/src/components/languages/LanguageFormDialog.tsx
  frontend/src/components/languages/index.tsx
Labels: refactor

#694 refactor(frontend): update nlpEntity dialogs
  frontend/src/components/nlp/NlpEntityDialog.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/components/nlp/components/NlpEntityFormDialog.tsx
Labels: refactor

#696 refactor(frontend): update nlpSample dialogs
  frontend/src/app-components/dialogs/FormDialog.tsx
  frontend/src/components/nlp/components/NlpSample.tsx
  frontend/src/components/nlp/components/NlpSampleForm.tsx
  frontend/src/components/nlp/components/NlpSampleFormDialog.tsx
  frontend/src/contexts/dialogs.context.tsx
  frontend/src/types/common/dialogs.types.ts
Labels: refactor

#698 refactor(frontend): update nlpValue dialogs
  frontend/src/components/nlp/NlpValueDialog.tsx
  frontend/src/components/nlp/components/NlpValue.tsx
  frontend/src/components/nlp/components/NlpValueForm.tsx
  frontend/src/components/nlp/components/NlpValueFormDialog.tsx
  frontend/src/components/nlp/index.tsx
Labels: refactor

#710 refactor(frontend): update subscriber dialogs
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/components/subscribers/EditSubscriberDialog.tsx
  frontend/src/components/subscribers/SubscriberForm.tsx
  frontend/src/components/subscribers/SubscriberFormDialog.tsx
  frontend/src/components/subscribers/index.tsx
Labels: refactor

#713 refactor(frontend): update EditUser & InviteUser dialogs
  frontend/src/app-components/buttons/FormButtons.tsx
  frontend/src/app-components/dialogs/FormDialog.tsx
  frontend/src/components/users/EditUserDialog.tsx
  frontend/src/components/users/EditUserForm.tsx
  frontend/src/components/users/EditUserFormDialog.tsx
  frontend/src/components/users/InvitationDialog.tsx
  frontend/src/components/users/InviteUserForm.tsx
  frontend/src/components/users/InviteUserFormDialog.tsx
  frontend/src/components/users/index.tsx
  frontend/src/types/common/dialogs.types.ts
Labels: refactor

#705 refactor(frontend): update menu dialogs
  frontend/src/components/Menu/MenuDialog.tsx
  frontend/src/components/Menu/MenuForm.tsx
  frontend/src/components/Menu/MenuFormDialog.tsx
  frontend/src/components/Menu/index.tsx
  frontend/src/utils/URL.ts
Labels: refactor

#721 refactor(frontend): update contentType dialogs
  frontend/src/components/content-types/ContentTypeDialog.tsx
  frontend/src/components/content-types/ContentTypeForm.tsx
  frontend/src/components/content-types/ContentTypeFormDialog.tsx
  frontend/src/components/content-types/index.tsx
Labels: refactor

#724 refactor(frontend): update content and contentImport dialogs
  frontend/src/app-components/buttons/FormButtons.tsx
  frontend/src/app-components/dialogs/GenericFormDialog.tsx
  frontend/src/components/contents/ContentForm.tsx
  frontend/src/components/contents/ContentFormDialog.tsx
  frontend/src/components/contents/ContentImportForm.tsx
  frontend/src/components/contents/ContentImportFormDialog.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/layout/themes/theme.ts
  frontend/src/pages/_app.tsx
Labels: refactor

#729 refactor(frontend): optimize useDialogs logic
  frontend/src/app-components/attachment/AttachmentForm.tsx
  frontend/src/app-components/dialogs/FormDialog.tsx
  frontend/src/components/Menu/MenuForm.tsx
  frontend/src/components/categories/CategoryForm.tsx
  frontend/src/components/content-types/ContentTypeForm.tsx
  frontend/src/components/contents/ContentForm.tsx
  frontend/src/components/contents/ContentImportForm.tsx
  frontend/src/components/context-vars/ContextVarForm.tsx
  frontend/src/components/inbox/components/AttachmentViewerForm.tsx
  frontend/src/components/labels/LabelForm.tsx
  frontend/src/components/languages/LanguageForm.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/components/nlp/components/NlpSampleForm.tsx
  frontend/src/components/nlp/components/NlpValueForm.tsx
  frontend/src/components/roles/PermissionsBody.tsx
  frontend/src/components/roles/RoleForm.tsx
  frontend/src/components/subscribers/SubscriberForm.tsx
  frontend/src/components/translations/TranslationForm.tsx
  frontend/src/components/users/EditUserForm.tsx
  frontend/src/components/users/InviteUserForm.tsx
  frontend/src/components/visual-editor/BlockEditForm.tsx
  frontend/src/components/visual-editor/BlockMoveForm.tsx
  frontend/src/types/common/dialogs.types.ts
Labels: refactor

#766 fix(api): update string and regex string zod validations
  api/src/chat/schemas/types/pattern.ts
  api/src/chat/services/block.service.ts
Labels: bug

#731 feat(frontend): introduce ESLint no-multiple-empty-lines rule
  api/.eslintrc.js
  frontend/.eslintrc.js
  frontend/src/app-components/attachment/AttachmentInput.tsx
  frontend/src/app-components/attachment/MultipleAttachmentInput.tsx
  frontend/src/app-components/inputs/AvatarInput.tsx
  frontend/src/app-components/inputs/FileInput.tsx
  frontend/src/app-components/tables/columns/renderPicture.tsx
  frontend/src/components/content-types/components/FieldInput.tsx
  frontend/src/components/inbox/components/Carousel.tsx
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/components/labels/index.tsx
  frontend/src/components/media-library/index.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpSample.tsx
  frontend/src/components/nlp/index.tsx
  frontend/src/components/profile/profile.tsx
  frontend/src/components/settings/SettingInput.tsx
  frontend/src/components/visual-editor/constants.ts
  frontend/src/components/visual-editor/form/AttachmentMessageForm.tsx
  frontend/src/components/visual-editor/form/inputs/triggers/PatternInput.tsx
  frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLinkFactory.tsx
  frontend/src/components/visual-editor/v2/CustomCanvasWidget.tsx
  frontend/src/components/visual-editor/v2/CustomDiagramNodes/NodeWidget.tsx
  frontend/src/hooks/useHasPermission.ts
  frontend/src/layout/themes/theme.ts
  frontend/src/pages/_app.tsx
  frontend/src/services/api.class.ts
  frontend/src/services/entities.ts
  frontend/src/services/types.ts
  frontend/src/types/attachment.types.ts
  frontend/src/types/base.types.ts
  frontend/src/types/block.types.ts
  frontend/src/types/model.types.ts
  frontend/src/types/user.types.ts
  widget/.eslintrc.json
  widget/src/ChatWidget.tsx
  widget/src/UiChatWidget.tsx
  widget/src/components/UserSubscription.tsx
  widget/src/utils/SocketIoClient.ts
  widget/src/utils/attachment.ts
Labels: enhancement

#761 fix(frontend): synchronize selected inbox subscriber with url query
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/pages/inbox/index.tsx
  frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx
  frontend/src/pages/inbox/subscribers/index.tsx
Labels: enhancement

#753 fix: make SettingType.select inferring options as type
  api/src/setting/index.d.ts
Labels: enhancement

#763 fix(frontend): use short dialogs imports
  frontend/src/components/Menu/MenuForm.tsx
  frontend/src/components/categories/CategoryForm.tsx
  frontend/src/components/content-types/ContentTypeForm.tsx
  frontend/src/components/contents/ContentForm.tsx
  frontend/src/components/contents/ContentImportForm.tsx
  frontend/src/components/context-vars/ContextVarForm.tsx
  frontend/src/components/labels/LabelForm.tsx
  frontend/src/components/languages/LanguageForm.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/components/nlp/components/NlpValueForm.tsx
  frontend/src/components/profile/profile.tsx
  frontend/src/components/roles/RoleForm.tsx
  frontend/src/components/subscribers/SubscriberForm.tsx
  frontend/src/components/users/EditUserForm.tsx
  frontend/src/components/users/InviteUserForm.tsx
  frontend/src/components/visual-editor/BlockEditForm.tsx
  frontend/src/components/visual-editor/BlockMoveForm.tsx
  frontend/src/components/visual-editor/form/MessageForm.tsx
  frontend/src/components/visual-editor/form/OptionsForm.tsx
  frontend/src/components/visual-editor/form/TriggersForm.tsx
Labels: enhancement

#779 fix(frontend): remove empty blank begin lines from the inbox pages
  frontend/src/app-components/inputs/Selectable.tsx
  frontend/src/components/nlp/components/NlpTrainForm.tsx
  frontend/src/pages/inbox/index.tsx
  frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx
  frontend/src/pages/inbox/subscribers/index.tsx
Labels: bug

#791 fix: add label bulk delete
  api/src/chat/controllers/label.controller.spec.ts
  api/src/chat/controllers/label.controller.ts
  api/src/chat/repositories/label.repository.ts
  api/src/chat/services/block.service.ts
  api/src/chat/services/subscriber.service.ts
  api/src/utils/test/fixtures/label.ts
  frontend/src/components/labels/index.tsx
Labels: needs-review

#789 fix: enhacement of content import
  api/src/cms/cms.module.ts
  api/src/cms/controllers/content.controller.spec.ts
  api/src/cms/controllers/content.controller.ts
  api/src/cms/services/content.service.spec.ts
  api/src/cms/services/content.service.ts
  frontend/src/components/contents/ContentImportForm.tsx
  frontend/src/components/contents/ContentImportFormDialog.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/hooks/crud/useImport.tsx
  frontend/src/services/api.class.ts
Labels: needs-review

#785 refactor: fixed the alignment of the button
  frontend/src/components/nlp/components/NlpSample.tsx
Labels: needs-review, SWOC

#767 Fixed carousel buttons not visible on dark image (black) and opening attachment from the inbox croping the image
  frontend/src/components/inbox/components/AttachmentViewerForm.tsx
  frontend/src/components/inbox/components/Carousel.tsx
Labels: needs-review, SWOC
