Repository Hexastack/Hexabot, pull requests merged in 2025-01, with the labels that each got.

#504 fix: restrict eslint license header year update to staged files
  .github/workflows/release.yml
  .husky/pre-commit
  api/.dockerignore
  api/.eslintrc-staged.js
  api/.eslintrc.js
  api/package-lock.json
  api/package.json
  frontend/.dockerignore
  frontend/.eslintrc-staged.js
  frontend/.eslintrc.js
  frontend/package.json
  widget/.dockerignore
  widget/.eslintrc-staged.json
  widget/.eslintrc.json
  widget/package.json
Labels: bug

#526 fix: disabled tsconfig strict Property Initialization
  api/tsconfig.json
Labels: enhancement

#530 [MERGE ORDER 2] fix: resolve search filterpipe null checks issues
  api/src/utils/pipes/search-filter.pipe.ts
  api/src/utils/types/filter.types.ts
Labels: strictNullChecks

#528 [MERGE ORDER 1] fix: resolve pagination-querypipe null checks issues
  api/src/utils/pagination/pagination-query.pipe.ts
Labels: strictNullChecks

#532 fix: CMS module issues
  api/src/attachment/services/attachment.service.ts
  api/src/chat/repositories/block.repository.ts
  api/src/chat/services/block.service.ts
  api/src/chat/services/bot.service.ts
  api/src/cms/controllers/content-type.controller.spec.ts
  api/src/cms/controllers/content.controller.spec.ts
  api/src/cms/controllers/content.controller.ts
  api/src/cms/controllers/menu.controller.spec.ts
  api/src/cms/controllers/menu.controller.ts
  api/src/cms/dto/content.dto.ts
  api/src/cms/repositories/content-type.repository.spec.ts
  api/src/cms/repositories/content-type.repository.ts
  api/src/cms/repositories/content.repository.spec.ts
  api/src/cms/schemas/content.schema.ts
  api/src/cms/services/content-type.service.spec.ts
  api/src/cms/services/content.service.spec.ts
  api/src/cms/services/content.service.ts
  api/src/cms/services/menu.service.ts
  api/src/cms/utilities/verifyTree.ts
  api/src/i18n/services/i18n.service.ts
  api/src/utils/generics/base-seeder.ts
  api/src/utils/test/fixtures/menu.ts
  api/src/utils/types/filter.types.ts
  frontend/src/components/contents/ContentDialog.tsx
  frontend/src/types/content.types.ts
Labels: strictNullChecks

#539 fix: User module issues
  api/src/user/controllers/auth.controller.spec.ts
  api/src/user/controllers/auth.controller.ts
  api/src/user/controllers/model.controller.spec.ts
  api/src/user/controllers/user.controller.spec.ts
  api/src/user/controllers/user.controller.ts
  api/src/user/dto/user.dto.ts
  api/src/user/guards/ability.guard.ts
  api/src/user/passport/session.serializer.ts
  api/src/user/repositories/invitation.repository.spec.ts
  api/src/user/repositories/model.repository.spec.ts
  api/src/user/repositories/user.repository.spec.ts
  api/src/user/schemas/user.schema.ts
  api/src/user/seeds/user.seed-model.ts
  api/src/user/services/auth.service.spec.ts
  api/src/user/services/invitation.service.spec.ts
  api/src/user/services/invitation.service.ts
  api/src/user/services/model.service.spec.ts
  api/src/user/services/passwordReset.service.spec.ts
  api/src/user/services/passwordReset.service.ts
  api/src/user/services/user.service.spec.ts
  api/src/user/services/validate-account.service.ts
  api/src/utils/test/fixtures/user.ts
  api/src/utils/types/filter.types.ts
Labels: strictNullChecks

#547 fix: apply strict null checks updates to the Chat Module
  api/src/channel/channel.service.ts
  api/src/channel/lib/__test__/subscriber.mock.ts
  api/src/chat/controllers/block.controller.spec.ts
  api/src/chat/controllers/block.controller.ts
  api/src/chat/controllers/context-var.controller.spec.ts
  api/src/chat/controllers/message.controller.spec.ts
  api/src/chat/controllers/subscriber.controller.spec.ts
  api/src/chat/controllers/subscriber.controller.ts
  api/src/chat/dto/block.dto.ts
  api/src/chat/repositories/block.repository.spec.ts
  api/src/chat/repositories/context-var.repository.ts
  api/src/chat/repositories/message.repository.spec.ts
  api/src/chat/repositories/subscriber.repository.spec.ts
  api/src/chat/repositories/subscriber.repository.ts
  api/src/chat/schemas/block.schema.ts
  api/src/chat/schemas/subscriber.schema.ts
  api/src/chat/schemas/types/channel.ts
  api/src/chat/services/block.service.spec.ts
  api/src/chat/services/block.service.ts
  api/src/chat/services/bot.service.spec.ts
  api/src/chat/services/bot.service.ts
  api/src/chat/services/chat.service.ts
  api/src/chat/services/conversation.service.ts
  api/src/chat/services/message.service.spec.ts
  api/src/chat/services/message.service.ts
  api/src/chat/services/subscriber.service.spec.ts
  api/src/chat/services/subscriber.service.ts
  api/src/extensions/channels/web/base-web-channel.ts
  api/src/extensions/channels/web/wrapper.ts
  api/src/nlp/services/nlp.service.ts
  api/src/utils/test/fixtures/block.ts
  api/src/utils/test/fixtures/conversation.ts
  api/src/utils/test/mocks/block.ts
  api/src/utils/test/mocks/subscriber.ts
  api/src/utils/test/sort.ts
  api/src/utils/types/filter.types.ts
Labels: strictNullChecks

#563 feat: implement strict null checks
  api/src/attachment/controllers/attachment.controller.spec.ts
  api/src/attachment/services/attachment.service.ts
  api/src/extensions/helpers/llm-nlu/index.helper.ts
  api/src/migration/migration.service.spec.ts
  api/src/migration/migration.service.ts
  api/src/migration/migrations/1735836154221-v-2-2-0.migration.ts
  api/src/migration/types.ts
  api/src/nlp/controllers/nlp-entity.controller.spec.ts
  api/src/nlp/controllers/nlp-value.controller.spec.ts
  api/src/nlp/controllers/nlp-value.controller.ts
  api/src/nlp/dto/nlp-value.dto.ts
  api/src/nlp/repositories/nlp-value.repository.spec.ts
  api/src/nlp/seeds/nlp-value.seed.ts
  api/src/nlp/services/nlp-value.service.spec.ts
  api/src/nlp/services/nlp-value.service.ts
  api/src/utils/generics/base-repository.ts
  api/src/utils/generics/base-service.ts
  api/src/utils/helpers/fs.ts
  api/src/utils/pipes/object-id.pipe.ts
  api/src/utils/test/fixtures/conversation.ts
  api/src/utils/test/fixtures/nlpvalue.ts
  api/tsconfig.json
Labels: strictNullChecks

#566 fix: missing value assignedAt
  api/src/chat/repositories/subscriber.repository.ts
Labels: important

#585 fix: remove delete opearation
  frontend/src/components/media-library/index.tsx
Labels: needs-review

#581 fix(frontend): resolve block list edit form bug
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
Labels: bug, needs-review

#645 fix: logout disconnection sockets
  api/src/user/controllers/auth.controller.ts
  api/src/websocket/websocket.gateway.ts
  api/types/event-emitter.d.ts
Labels: bug

#653 fix: resolve broadcastChannel duplication tab bug
  frontend/src/contexts/broadcast-channel.context.tsx
  widget/src/providers/BroadcastChannelProvider.tsx
  widget/src/utils/generateId.ts
  widget/src/utils/safeRandom.ts
Labels: bug
