Repository Hexastack/Hexabot, pull requests merged in 2025-04, with the labels that each got.

#852 feat: centrelize logger
  api/src/analytics/services/bot-stats.service.ts
  api/src/app.controller.ts
  api/src/attachment/controllers/attachment.controller.ts
  api/src/attachment/services/attachment.service.ts
  api/src/chat/controllers/block.controller.ts
  api/src/chat/controllers/category.controller.ts
  api/src/chat/controllers/context-var.controller.ts
  api/src/chat/controllers/label.controller.ts
  api/src/chat/controllers/message.controller.ts
  api/src/chat/controllers/subscriber.controller.ts
  api/src/chat/repositories/block.repository.ts
  api/src/chat/services/block.service.ts
  api/src/chat/services/conversation.service.ts
  api/src/chat/services/message.service.ts
  api/src/chat/services/subscriber.service.ts
  api/src/cms/controllers/content-type.controller.ts
  api/src/cms/controllers/content.controller.ts
  api/src/cms/controllers/menu.controller.ts
  api/src/cms/services/content.service.ts
  api/src/i18n/controllers/language.controller.ts
  api/src/i18n/controllers/translation.controller.ts
  api/src/i18n/services/language.service.ts
  api/src/nlp/controllers/nlp-entity.controller.ts
  api/src/nlp/controllers/nlp-sample.controller.ts
  api/src/nlp/controllers/nlp-value.controller.ts
  api/src/nlp/services/nlp-sample.service.ts
  api/src/setting/services/setting.service.ts
  api/src/user/controllers/permission.controller.ts
  api/src/user/controllers/role.controller.ts
  api/src/user/controllers/user.controller.ts
  api/src/user/services/invitation.service.spec.ts
  api/src/user/services/invitation.service.ts
  api/src/utils/generics/base-controller.ts
  api/src/utils/generics/base-repository.ts
  api/src/utils/generics/base-service.ts
  api/src/utils/test/dummy/dummy.module.ts
  api/src/websocket/services/socket-event-dispatcher.service.ts
Labels: enhancement

#750 fix: write an end-to-end contribution flow
  CONTRIBUTING.md
Labels: enhancement

#894 fix: importing csv file ignores fields and status always true
  api/src/cms/services/content.service.ts
Labels: bug

#899 fix: add missing content payloadType
  api/src/chat/controllers/block.controller.spec.ts
  api/src/chat/schemas/types/button.ts
Labels: bug, needs-review

#910 Fix: Make translatable plugin settings
  api/src/i18n/services/translation.service.ts
Labels: bug

#904 fix(frontend): align BlockFormProvider method prop and the useForm typing
  frontend/src/components/visual-editor/form/BlockFormProvider.tsx
Labels: bug

#909 Chore: update dependencies category
  api/package-lock.json
  api/package.json
  frontend/package.json
  package-lock.json
  widget/package.json
Labels: enhancement

#918 fix(api): resolve getAllowsOrigins bug
  api/src/main.ts
  api/src/setting/services/setting.service.spec.ts
  api/src/setting/services/setting.service.ts
  api/src/websocket/utils/gateway-options.ts
Labels: bug

#812 feat: display synonyms inputs
  frontend/src/components/nlp/components/NlpValue.tsx
  frontend/src/components/nlp/components/NlpValueForm.tsx
  frontend/src/components/nlp/components/NlpValueFormDialog.tsx
Labels: needs-review

#919 fix(api): optimize preUpdateMany
  api/src/chat/repositories/block.repository.spec.ts
  api/src/chat/repositories/block.repository.ts
Labels: enhancement

#871 fix: cleanup languageId from NlpSamples on language deletion
  api/src/i18n/repositories/language.repository.ts
  api/src/nlp/services/nlp-sample.service.ts
Labels: needs-review

#554 fix(frontend): allow fallback block to be empty
  frontend/src/components/settings/SettingInput.tsx
Labels: needs-review, SWOC

#920 feat: add loading spinner for document upload
  frontend/src/app-components/attachment/AttachmentUploader.tsx
Labels: enhancement

#341 fix(frontend): date normalization
  frontend/src/components/inbox/components/Chat.tsx
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/utils/date.ts
Labels: bug

#926 Add missing support for GIF upload
  frontend/src/utils/attachment.ts
Labels: needs-review, v2.2.6

#927 fix: backward compatibility content type fields type
  api/src/cms/dto/contentType.dto.ts
Labels: needs-review, v2.2.6

#932 fix(widget): support GIF images
  widget/src/utils/attachment.ts
Labels: needs-review, v2.2.6

#923 fix(api): resolve messages order response
  api/src/chat/services/bot.service.ts
  api/src/chat/services/chat.service.ts
Labels: bug, needs-review, v2.2.6

#940 fix: correct criteria format for nlp value update
  api/src/nlp/repositories/nlp-entity.repository.ts
  api/src/nlp/services/nlp.service.ts
Labels: needs-review

#913 Fix: attachment issues
  api/src/channel/lib/Handler.ts
  api/src/channel/webhook.controller.ts
  api/src/chat/chat.module.ts
  api/src/chat/services/message.service.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/components/inbox/components/AttachmentViewer.tsx
  widget/src/components/messages/FileMessage.scss
  widget/src/components/messages/FileMessage.tsx
  widget/src/translations/en/translation.json
  widget/src/translations/fr/translation.json
Labels: needs-review, v2.2.6

#949 Filter out wildcard origins from allowed domains
  api/src/extensions/channels/web/base-web-channel.ts
Labels: needs-review

#944 fix: Resolve block local fallback issue
  api/src/chat/services/bot.service.ts
  frontend/src/components/visual-editor/constants.ts
  frontend/src/components/visual-editor/form/inputs/options/LocalFallbackInput.tsx
Labels: bug, v2.2.6
