Repository Hexastack/Hexabot, pull requests merged in 2025-07, with the labels that each got.

#1168 fix(api): add a TTL cache env variable
  api/src/config/index.ts
  docker/.env.example
Labels: needs-review, urgent

#1174 fix(frontend): clear React Query cache ondisconnect
  frontend/src/hooks/entities/auth-hooks.ts
Labels: bug, needs-review, urgent

#1172 fix(api): update lastvisit and retainedfrom defaultvalues
  api/src/chat/schemas/subscriber.schema.ts
  api/src/utils/test/fixtures/subscriber.ts
Labels: bug, needs-review, urgent

#1180 refactor(api): replace findPage & findPageAndPopulate deprecated methods
  api/src/chat/repositories/label.repository.spec.ts
  api/src/chat/repositories/message.repository.spec.ts
  api/src/chat/repositories/subscriber.repository.spec.ts
  api/src/chat/services/block.service.spec.ts
  api/src/chat/services/label.service.spec.ts
  api/src/chat/services/message.service.spec.ts
  api/src/chat/services/subscriber.service.spec.ts
  api/src/cms/repositories/content.repository.spec.ts
  api/src/cms/services/content.service.spec.ts
  api/src/i18n/controllers/language.controller.spec.ts
  api/src/i18n/controllers/translation.controller.spec.ts
  api/src/nlp/repositories/nlp-sample-entity.repository.spec.ts
  api/src/nlp/repositories/nlp-sample.repository.spec.ts
  api/src/nlp/services/nlp-entity.service.spec.ts
  api/src/nlp/services/nlp-sample-entity.service.spec.ts
  api/src/nlp/services/nlp-sample.service.spec.ts
  api/src/user/controllers/user.controller.spec.ts
  api/src/user/repositories/invitation.repository.spec.ts
  api/src/user/repositories/role.repository.spec.ts
  api/src/user/repositories/user.repository.spec.ts
  api/src/user/services/role.service.spec.ts
  api/src/user/services/user.service.spec.ts
Labels: enhancement, needs-review, urgent

#1184 fix(widget): centered disconnected content
  widget/src/components/ConnectionLost.scss
Labels: bug

#1197 fix(api): add Date support to flatten function
  api/src/utils/helpers/flatten.spec.ts
  api/src/utils/helpers/flatten.ts
Labels: bug, important, needs-review

#1120 Revise and expand block update tests
  api/src/chat/repositories/block.repository.spec.ts
  api/src/chat/repositories/block.repository.ts
  frontend/public/locales/en/translation.json
  frontend/public/locales/fr/translation.json
  frontend/src/components/visual-editor/v2/Diagrams.tsx
Labels: needs-review

#1238 fix: Enhance DTO/Schema validations / UI Toast error presentation
  api/src/chat/dto/block.dto.ts
  api/src/chat/dto/message.dto.ts
  api/src/chat/dto/subscriber.dto.ts
  api/src/chat/schemas/types/message.ts
  api/src/chat/schemas/types/options.ts
  api/src/chat/schemas/types/pattern.ts
  api/src/chat/validation-rules/is-channel-data.ts
  api/src/chat/validation-rules/is-message.ts
  api/src/chat/validation-rules/is-pattern-list.ts
  api/src/chat/validation-rules/is-position.ts
  api/src/chat/validation-rules/is-valid-capture.ts
  api/src/chat/validation-rules/is-valid-message-text.ts
  api/src/cms/services/content.service.spec.ts
  api/src/utils/decorators/validate.decorator.ts
  api/src/utils/generics/base-service.ts
  api/src/utils/helpers/zod-validation.ts
  api/src/utils/test/mocks/block.ts
  frontend/src/components/Menu/MenuForm.tsx
  frontend/src/components/categories/CategoryForm.tsx
  frontend/src/components/categories/index.tsx
  frontend/src/components/content-types/ContentTypeForm.tsx
  frontend/src/components/content-types/index.tsx
  frontend/src/components/contents/ContentForm.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/components/context-vars/ContextVarForm.tsx
  frontend/src/components/labels/LabelForm.tsx
  frontend/src/components/nlp/components/NlpEntityForm.tsx
  frontend/src/components/nlp/components/NlpValue.tsx
  frontend/src/components/roles/PermissionsBody.tsx
  frontend/src/components/translations/TranslationForm.tsx
  frontend/src/components/users/EditUserForm.tsx
  frontend/src/components/users/index.tsx
  frontend/src/components/visual-editor/BlockEditForm.tsx
  frontend/src/components/visual-editor/constants.ts
  frontend/src/components/visual-editor/form/ListMessageForm.tsx
  frontend/src/components/visual-editor/form/OptionsForm.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/types/message.types.ts
Labels: needs-review

#1250 fix(frontend): enhance SearchPayload typing [main<-1247]
  frontend/src/app-components/inputs/AutoCompleteEntitySelect.tsx
  frontend/src/app-components/inputs/NlpPatternSelect.tsx
  frontend/src/components/categories/index.tsx
  frontend/src/components/content-types/index.tsx
  frontend/src/components/contents/index.tsx
  frontend/src/components/context-vars/index.tsx
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/components/inbox/hooks/useInfiniteLiveMessages.ts
  frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts
  frontend/src/components/inbox/index.tsx
  frontend/src/components/labels/index.tsx
  frontend/src/components/languages/index.tsx
  frontend/src/components/media-library/index.tsx
  frontend/src/components/nlp/components/NlpEntity.tsx
  frontend/src/components/nlp/components/NlpSample.tsx
  frontend/src/components/nlp/components/NlpValue.tsx
  frontend/src/components/roles/index.tsx
  frontend/src/components/subscribers/index.tsx
  frontend/src/components/translations/index.tsx
  frontend/src/components/users/index.tsx
  frontend/src/components/visual-editor/v2/Diagrams.tsx
  frontend/src/hooks/crud/useFind.tsx
  frontend/src/hooks/useSearch.tsx
  frontend/src/types/attachment.types.ts
  frontend/src/types/base.types.ts
  frontend/src/types/block.types.ts
  frontend/src/types/language.types.ts
  frontend/src/types/nlp-entity.types.ts
  frontend/src/types/nlp-sample.types.ts
  frontend/src/types/search.types.ts
  frontend/src/types/subscriber.types.ts
Labels: needs-review, 🪄 Investigate

#1253 fix(frontend): update useInfiniteFind typing
  frontend/src/hooks/crud/useInfiniteFind.ts
  frontend/src/hooks/crud/useNormalizedInfiniteQuery.ts
Labels: needs-review, 🪄 Investigate

#1270 fix(widget): resolve link hover colors
  widget/src/components/messages/TextMessage.tsx
  widget/src/constants/colors.ts
  widget/src/types/colors.types.ts
Labels: needs-review

#1279 fix(api): resolve translation generation issue
  api/src/i18n/services/translation.service.ts
Labels: bug
