Repository Hexastack/Hexabot, pull requests merged in 2025-06, with the labels that each got.

#1075 fix(frontend): resolve useInfiniteLiveSubscribers hook or operator bug
  frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts
Labels: bug, needs-review

#1072 fix(frontend): resolve inbox flickering issue
  frontend/src/components/inbox/components/ConversationsList.tsx
  frontend/src/components/inbox/index.tsx
Labels: bug, needs-review

#1079 fix(api): add textarea & secret missed types to the settings type
  api/src/setting/schemas/types.ts
Labels: needs-review

#1077 fix(frontend): make quickReplies response message required
  frontend/src/components/visual-editor/form/QuickRepliesMessageForm.tsx
Labels: bug, needs-review

#1074 fix(frontend): fix category redirection to the visual editor
  frontend/src/components/categories/CategoryForm.tsx
Labels: bug, needs-review

#1080 feat(api): add strict Setting types
  api/src/channel/types.ts
  api/src/helper/types.ts
  api/src/plugins/types.ts
  api/src/setting/schemas/types.ts
Labels: enhancement, needs-review

#1090 Update autoLink logic to process all message directions consistently
  widget/src/components/messages/TextMessage.tsx
Labels: needs-review

#1089 feat(inbox): Only update subscriber cache when no filters are active
  frontend/src/components/inbox/hooks/useInfiniteLiveSubscribers.ts
Labels: needs-review

#1098 refactor: rename populate
  api/src/chat/repositories/subscriber.repository.ts
  api/src/utils/generics/base-repository.ts
Labels: needs-review

#1113 fix(frontend): resolve label updates
  frontend/src/app-components/inputs/AutoCompleteSelect.tsx
Labels: bug

#1110 fix(api): remove unused returns
  api/src/extensions/channels/web/base-web-channel.ts
  api/src/nlp/services/nlp.service.ts
Labels: needs-review, 🪄 Investigate

#1133 fix(api): resolve predefined create hooks bug
  api/src/chat/repositories/label.repository.ts
  api/src/nlp/repositories/nlp-entity.repository.spec.ts
  api/src/nlp/repositories/nlp-entity.repository.ts
  api/src/nlp/repositories/nlp-value.repository.spec.ts
  api/src/nlp/repositories/nlp-value.repository.ts
  api/src/nlp/services/nlp.service.ts
  api/types/event-emitter.d.ts
Labels: bug, needs-review

#1135 fix(api): resolve predefined update hooks bug
  api/src/nlp/repositories/nlp-entity.repository.spec.ts
  api/src/nlp/repositories/nlp-entity.repository.ts
  api/src/nlp/repositories/nlp-value.repository.spec.ts
  api/src/nlp/repositories/nlp-value.repository.ts
  api/src/nlp/services/nlp.service.ts
  api/types/event-emitter.d.ts
Labels: bug, needs-review

#1151 fix(frontend): resolve Nlu selection bug
  frontend/src/app-components/inputs/Selectable.tsx
  frontend/src/components/nlp/components/NlpTrainForm.tsx
Labels: bug

#1162 fix(widget): resolve long message cropped bug
  widget/src/components/Message.scss
Labels: bug

#1164 fix(widget): break messages by words
  widget/src/components/Message.scss
Labels: needs-review
